"""Domain layer: shared constants and typed data structures.

No Streamlit, routing, or solver-library dependencies. See ``constants.py``
and ``types.py``.
"""

from domain.constants import (
    CARRIED_PIECES,
    DEFAULT_GAMMA,
    DEFAULT_INCIDENT_LOCATION,
    DEFAULT_MAX_LINES_PER_HYDRANT,
    DEFAULT_MAX_RADIUS,
    DEFAULT_PLANNING_RESERVE_PERCENT,
    DEFAULT_Q,
    DEFAULT_RADIUS_STEP,
    DEFAULT_START_RADIUS,
    DEFAULT_V,
    FLOW_TOL,
    HOSE_PIECE_M,
    MIN_DISTANCE_M,
    MODEL_LABELS,
    MODEL_NAMES,
    MODEL_OPTION_LABELS,
    RECOVER_FAILED_HYDRANT_HOSE,
    flow_tolerance,
)
from domain.capacity import (
    deployment_time,
    hose_pieces,
    max_usable_capacity,
    usable_capacity,
)
from domain.types import (
    AvailabilityEvent,
    DispatcherPreference,
    FlowStatus,
    HydrantCandidate,
    HydrantLine,
    IncidentRequest,
    ModelResult,
    Params,
    Plan,
    Scenario,
    ScenarioMessage,
    UpdateFacts,
)

__all__ = [
    "CARRIED_PIECES",
    "DEFAULT_GAMMA",
    "DEFAULT_INCIDENT_LOCATION",
    "DEFAULT_MAX_LINES_PER_HYDRANT",
    "DEFAULT_MAX_RADIUS",
    "DEFAULT_PLANNING_RESERVE_PERCENT",
    "DEFAULT_Q",
    "DEFAULT_RADIUS_STEP",
    "DEFAULT_START_RADIUS",
    "DEFAULT_V",
    "FLOW_TOL",
    "HOSE_PIECE_M",
    "MIN_DISTANCE_M",
    "MODEL_LABELS",
    "MODEL_NAMES",
    "MODEL_OPTION_LABELS",
    "RECOVER_FAILED_HYDRANT_HOSE",
    "flow_tolerance",
    "hose_pieces",
    "usable_capacity",
    "max_usable_capacity",
    "deployment_time",
    "AvailabilityEvent",
    "DispatcherPreference",
    "FlowStatus",
    "HydrantCandidate",
    "HydrantLine",
    "IncidentRequest",
    "ModelResult",
    "Params",
    "Plan",
    "Scenario",
    "ScenarioMessage",
    "UpdateFacts",
]
